#!/usr/bin/env bash
# Usage: update-index.sh <vault_path>
# Regenerates index.md from wiki pages using Obsidian CLI (property:read for tldr).
set -Eeuo pipefail
[[ ${BASH_VERSINFO[0]:-0} -ge 4 ]] && shopt -s inherit_errexit
umask 077

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
# shellcheck source=./lib/read-yaml-key.sh
source "$SCRIPT_DIR/lib/read-yaml-key.sh"

VAULT_PATH=""; FORCE=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --force) FORCE=1; shift ;;
    -h|--help) echo "Usage: update-index.sh <vault_path> [--force]" >&2; exit 0 ;;
    --) shift; [[ $# -gt 0 ]] && VAULT_PATH="$1"; break ;;
    -*) echo "Unknown arg: $1" >&2; exit 2 ;;
    *) VAULT_PATH="$1"; shift ;;
  esac
done
[[ -n "$VAULT_PATH" ]] || { echo "Usage: update-index.sh <vault_path> [--force]" >&2; exit 2; }

PROJECT=$(lib_read_yaml_key "${VAULT_PATH}/wiki.config.md" "project")
PROJECT="${PROJECT:-Wiki}"
WIKI_DIR="${VAULT_PATH}/wiki"
INDEX="${VAULT_PATH}/index.md"

# Auto-index region markers. Only content BETWEEN these is machine-managed;
# everything outside is hand-curated narrative the script must never clobber.
readonly AUTO_START="<!-- wiki:auto-index:start -->"
readonly AUTO_END="<!-- wiki:auto-index:end -->"

if [[ ! -d "$WIKI_DIR" ]]; then
  echo "Error: wiki/ directory not found at ${WIKI_DIR}" >&2
  exit 1
fi

OBS_VAULT=$(lib_read_yaml_key "${VAULT_PATH}/wiki.config.md" "vault_name")
if [[ -z "$OBS_VAULT" ]]; then
  echo "Error: vault_name not found in wiki.config.md" >&2
  exit 1
fi

# Section order: "dir:Display Name"
SECTIONS="concepts:Concepts
entities:Entities
architecture:Architecture
decisions:Decisions
strategy:Strategy
orgs:Organizations
comparisons:Comparisons
open-questions:Open Questions
sources:Source Summaries
synthesis:Synthesis"

# Fail fast: an existing index without sentinels (and no --force) cannot be
# safely regenerated — refuse before any expensive page scanning, so we never
# destroy hand-curated narrative (#5).
if [[ -f "$INDEX" && "$FORCE" -ne 1 ]] \
   && ! { grep -qF "$AUTO_START" "$INDEX" && grep -qF "$AUTO_END" "$INDEX"; }; then
  {
    echo "Refusing to overwrite $INDEX: no auto-index sentinels found."
    echo "Regenerating from scratch would destroy hand-curated narrative."
    echo "Either:"
    echo "  1. Insert the markers where the page list belongs, then re-run (merge preserves the rest):"
    echo "       $AUTO_START"
    echo "       $AUTO_END"
    echo "  2. Or re-run with --force to rebuild the whole file (narrative is lost)."
  } >&2
  exit 3
fi

TODAY=$(date +%Y-%m-%d)
TOTAL=0

# Count all pages first
while IFS=: read -r dir display; do
  files=$(obsidian vault="$OBS_VAULT" files folder="wiki/$dir" < /dev/null 2>/dev/null | grep -v '/_hub\.md$' || true)
  [[ -z "$files" ]] && continue
  count=$(echo "$files" | wc -l | tr -d ' ')
  TOTAL=$((TOTAL + count))
done <<< "$SECTIONS"

# Build the auto-generated page listing (everything that lives between the
# sentinels). Narrative outside the sentinels is owned by humans, not here.
AUTO=""
while IFS=: read -r dir display; do
  files=$(obsidian vault="$OBS_VAULT" files folder="wiki/$dir" < /dev/null 2>/dev/null | grep -v '/_hub\.md$' | sort || true)
  [[ -z "$files" ]] && continue

  count=$(echo "$files" | wc -l | tr -d ' ')

  AUTO+="
## ${display} (${count} pages)

"

  while IFS= read -r filepath; do
    slug=$(basename "$filepath" .md)
    tldr=$(obsidian vault="$OBS_VAULT" property:read name=tldr path="$filepath" < /dev/null 2>/dev/null || echo "")
    # Truncate to ~120 chars for readability
    if [[ ${#tldr} -gt 120 ]]; then
      tldr="${tldr:0:120}"
    fi
    if [[ -n "$tldr" ]]; then
      AUTO+="- [[${slug}]] -- ${tldr}
"
    else
      AUTO+="- [[${slug}]]
"
    fi
  done <<< "$files"
done <<< "$SECTIONS"

AUTO_BLOCK="${AUTO_START}
<!-- Generated by update-index.sh — content here is overwritten on each run. Curate narrative OUTSIDE this block. -->
${AUTO}
${AUTO_END}"

# Merge mode (default): if the index already carries both sentinels, replace
# only the region between them and keep all hand-curated content intact (#5).
if [[ -f "$INDEX" ]] && grep -qF "$AUTO_START" "$INDEX" && grep -qF "$AUTO_END" "$INDEX"; then
  TMP_BLOCK=$(mktemp "${TMPDIR:-/tmp}/wiki-index-block.XXXXXX")
  trap 'rm -f "$TMP_BLOCK"' EXIT
  printf '%s' "$AUTO_BLOCK" > "$TMP_BLOCK"
  START="$AUTO_START" END="$AUTO_END" BLOCK_FILE="$TMP_BLOCK" python3 - "$INDEX" <<'PY'
import os, sys
path = sys.argv[1]
start, end = os.environ["START"], os.environ["END"]
with open(os.environ["BLOCK_FILE"]) as f:
    block = f.read()
with open(path) as f:
    text = f.read()
i = text.find(start)
j = text.find(end)
if i == -1 or j == -1 or j < i:
    sys.stderr.write("sentinels not found or out of order; aborting\n")
    sys.exit(4)
j += len(end)
with open(path, "w") as f:
    f.write(text[:i] + block + text[j:])
PY
  echo "index.md merged: ${TOTAL} pages (narrative preserved)"
  exit 0
fi

# Fresh build: no index yet, or --force. Embed the sentinels so subsequent runs
# merge instead of clobber.
OUTPUT="---
title: ${PROJECT} Wiki Index
updated: ${TODAY}
last_ingest: ${TODAY}
status: active
page_count: ${TOTAL}
tags:
  - index
  - meta
---

# ${PROJECT} Wiki

> [!info] Wiki Entry Point
> This is the starting point for navigating the wiki.
> Updated on every ingest. LLM reads this first when answering queries.

${AUTO_BLOCK}

---

## Recent Activity

See [[log]] for the full change log.
"

printf '%s' "$OUTPUT" > "$INDEX"
if [[ "$FORCE" -eq 1 ]]; then
  echo "index.md rebuilt (--force): ${TOTAL} pages across 10 domains"
else
  echo "index.md created: ${TOTAL} pages across 10 domains"
fi
